# Generated by Django 6.0.3 on 2026-04-01 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='manager',
        ),
        migrations.AddField(
            model_name='team',
            name='draw',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='goal_difference',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='lose',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='win',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='league.team')),
            ],
        ),
        migrations.DeleteModel(
            name='LeagueTable',
        ),
    ]
