# Generated by Django 6.0.3 on 2026-04-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_remove_team_manager_team_draw_team_goal_difference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='managers/'),
        ),
    ]
