# Generated by Django 6.0.3 on 2026-04-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_manager_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='team',
        ),
        migrations.AddField(
            model_name='manager',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manager',
            name='contact',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
