# Generated by Django 6.0.3 on 2026-04-01 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_remove_manager_team_manager_age_manager_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='league.team'),
        ),
    ]
